apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx2
          image: nginx:stable
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "Europe/Moscow"
            
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Moscow
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: observability
spec:
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
