apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: observability
spec:
  selector:
    app: victoria-metrics
  ports:
    - port: 8428
      targetPort: 8428
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:latest
          args:
            - '--selfScrapeInterval=0'
            - '--storageDataPath=/victoria-metrics-data'   # Specify storage path
            - '--retentionPeriod=30d'                      # Retain data for 30 days
          env:
            - name: TZ
              value: "Europe/Moscow"
          volumeMounts:
            - name: victoria-metrics-storage
              mountPath: /victoria-metrics-data           # Mount storage volume
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: victoria-metrics-storage
          persistentVolumeClaim:
            claimName: victoria-metrics-pvc
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Moscow
            type: File
