apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      containers:
        - name: vmagent
          image: victoriametrics/vmagent:latest
          args:
            - '--promscrape.config=/etc/vmagent/vmagent.yaml'
            - '--remoteWrite.url=http://victoria-metrics:8428/api/v1/write'
            - '--httpListenAddr=:8429'
          env:
            - name: TZ
              value: "Europe/Moscow"
          volumeMounts:
            - name: config
              mountPath: /etc/vmagent
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
        - name: config-reloader
          image: jimmidyson/configmap-reload:v0.5.0
          args:
            - --volume-dir=/etc/vmagent
            - --webhook-url=http://localhost:8429/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/vmagent
      volumes:
        - name: config
          configMap:
            name: vmagent-scrape-config
            items:
              - key: vmagent.yaml
                path: vmagent.yaml
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Moscow
            type: File
