apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-rules
  namespace: observability
data:
  rules.yaml: |
    groups:
      - name: availability-rules
        rules:
          - alert: EndpointDown
            expr: probe_success == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Endpoint {{ $labels.instance }} is down"
              description: "The endpoint {{ $labels.instance }} has been down for more than 1 minute."
