apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  config.yml: |
    global:
      smtp_smarthost: 'mailhog:1025'
      smtp_from: 'alertmanager@example.com'
    route:
      receiver: 'email-alert'
    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'user@example.com'
            # Uncomment and set your real email configurations here
            # smtp_smarthost: 'smtp.example.com:587'
            # smtp_from: 'alertmanager@example.com'
            # auth_username: 'your-username'
            # auth_password: 'your-password'
